#!/usr/bin/env bash
# Shared helpers for herdr plugin scripts on macOS / Linux / WSL2.
# Source with:  . "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
#
# UNVERIFIED: this branch was ported from the Windows implementation and has not been
# run against a real herdr on a POSIX host. Run the installer's self-test and trust
# its output over these comments.

# No `set -e` on purpose: git exits non-zero for ordinary conditions (empty diff,
# missing upstream) and killing the script on those would be wrong.
set -uo pipefail

HERDR="${HERDR_BIN_PATH:-herdr}"
_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# settings.sh is generated by the installer and lives next to these scripts.
. "$_LIB_DIR/settings.sh"

h_json() { "$HERDR" "$@" 2>/dev/null; }

# Pull a value out of JSON without depending on jq (not guaranteed present).
# Usage: h_jq '<python expression over `d`>' <<< "$json"
h_jq() {
  python3 -c "
import json,sys
try:
    d = json.load(sys.stdin)
except Exception:
    sys.exit(0)
try:
    v = $1
except Exception:
    sys.exit(0)
if v is not None:
    print(v)
" 2>/dev/null
}

h_notify() {
  local title="$1" body="${2:-}" sound="${3:-}"
  local a=(notification show "$title")
  [ -n "$body" ]  && a+=(--body "$body")
  [ -n "$sound" ] && a+=(--sound "$sound")
  "$HERDR" "${a[@]}" >/dev/null 2>&1
}

# --- Plugin JSON shapes (confirm with the calibration probe before trusting) ----
#
# HERDR_PLUGIN_CONTEXT_JSON is FLAT:
#   workspace_id, workspace_label, workspace_cwd, tab_id, tab_label,
#   focused_pane_id, focused_pane_cwd, focused_pane_status,
#   invocation_source, correlation_id
#   + worktree { repo_key, repo_name, repo_root, checkout_path, is_linked_worktree }
#
# HERDR_PLUGIN_EVENT_JSON:
#   workspace.created -> { event, data { type, workspace { ..., worktree? } } }
#                        NOTE: no cwd, no branch
#   worktree.created  -> { event, data { type, workspace {...},
#                          worktree { path, branch, open_workspace_id, ... } } }
#
# BOTH events fire for the same new worktree.

h_ctx() { printf '%s' "${HERDR_PLUGIN_CONTEXT_JSON:-}"; }
h_ev()  { printf '%s' "${HERDR_PLUGIN_EVENT_JSON:-}"; }

# herdr may return a path with a trailing separator. On POSIX there are no mixed
# separators, but normalise anyway so callers can compare paths.
h_path() {
  local p="${1:-}"
  [ -z "$p" ] && return 0
  p="${p%/}"
  printf '%s' "$p"
}

h_workspace_id() {
  if [ -n "${HERDR_WORKSPACE_ID:-}" ]; then printf '%s' "$HERDR_WORKSPACE_ID"; return 0; fi
  h_json pane current | h_jq "d['result']['pane']['workspace_id']"
}

# HERDR_ACTIVE_PANE_CWD / HERDR_ACTIVE_WORKSPACE_ID are NOT set in plugin or keybinding
# context. `workspace get` has no cwd field at all - only panes and worktrees carry a
# path.
h_cwd() {
  local ctx d
  ctx="$(h_ctx)"
  if [ -n "$ctx" ]; then
    d="$(printf '%s' "$ctx" | h_jq "d.get('worktree',{}).get('checkout_path')")"
    [ -n "$d" ] && { h_path "$d"; return 0; }
    d="$(printf '%s' "$ctx" | h_jq "d.get('focused_pane_cwd')")"
    [ -n "$d" ] && { h_path "$d"; return 0; }
    d="$(printf '%s' "$ctx" | h_jq "d.get('workspace_cwd')")"
    [ -n "$d" ] && { h_path "$d"; return 0; }
  fi
  if [ -n "${HERDR_PANE_ID:-}" ]; then
    d="$(h_json pane get "$HERDR_PANE_ID" | h_jq "d['result']['pane'].get('cwd')")"
    [ -n "$d" ] && { h_path "$d"; return 0; }
  fi
  # Keybinding commands get no plugin context - ask the server for the focused pane.
  d="$(h_json pane current | h_jq "d['result']['pane'].get('cwd')")"
  [ -n "$d" ] && { h_path "$d"; return 0; }
  printf '%s' "$PWD"
}

# `workspace list/get` has NO cwd field.
h_workspace_path() {
  local ws="${1:-}" d
  [ -z "$ws" ] && return 0
  d="$(h_json workspace get "$ws" | h_jq "d['result']['workspace'].get('worktree',{}).get('checkout_path')")"
  [ -n "$d" ] && { h_path "$d"; return 0; }
  d="$(h_json pane list --workspace "$ws" | h_jq "next((p['cwd'] for p in d['result']['panes'] if p.get('cwd')), None)")"
  [ -n "$d" ] && { h_path "$d"; return 0; }
  return 0
}

h_git_root() {
  local dir="${1:-}"
  [ -z "$dir" ] && dir="$(h_cwd)"
  git -C "$dir" rev-parse --show-toplevel 2>/dev/null
}

h_base_branch() {
  local dir="${1:-.}" b c
  b="$(git -C "$dir" symbolic-ref -q --short refs/remotes/origin/HEAD 2>/dev/null)"
  [ -n "$b" ] && { printf '%s' "$b"; return 0; }
  for c in origin/main origin/master main master; do
    if git -C "$dir" rev-parse --verify -q "$c" >/dev/null 2>&1; then printf '%s' "$c"; return 0; fi
  done
  printf 'HEAD'
}

h_slug() {
  local s
  s="$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]\{1,\}/-/g; s/^-//; s/-$//')"
  case "$s" in [a-z]*) ;; *) s="a$s" ;; esac
  printf '%.32s' "$s"
}

h_pane_of_workspace() {
  h_json pane list --workspace "$1" | h_jq "
next((p['pane_id'] for p in d['result']['panes'] if p.get('focused')),
     d['result']['panes'][0]['pane_id'] if d['result']['panes'] else None)"
}

# `agent start` needs a pane already at an interactive shell prompt. It never creates or
# moves panes. Everything after `--` is passed through to the agent.
h_start_agent() {
  local pane="$1" label="$2" prompt="${3:-}"
  local name out i live
  name="a-$(h_slug "$label")"
  # chr(10) rather than a backslash escape - the expression travels through a
  # double-quoted bash string and an escape would be ambiguous.
  live="$(h_json agent list | h_jq "chr(10).join(a['name'] for a in d['result']['agents'] if a.get('name'))")"
  if printf '%s\n' "$live" | grep -qx "$name"; then
    name="${name:0:27}-$RANDOM"
  fi

  for i in 1 2 3 4 5 6; do
    # shellcheck disable=SC2086
    out="$("$HERDR" agent start "$name" --kind "$AGENT_KIND" --pane "$pane" -- $AGENT_ARGS 2>&1)"
    case "$out" in
      *'"error"'*) sleep 1.5 ;;
      *) [ -n "$prompt" ] && "$HERDR" agent prompt "$name" "$prompt" >/dev/null 2>&1
         printf '%s' "$name"; return 0 ;;
    esac
  done
  printf 'agent start failed: %s\n' "$out" >&2
  return 1
}

# Raw socket API over the unix socket at HERDR_SOCKET_PATH.
# UNVERIFIED on POSIX. On Windows the server is one-shot per connection; assume the same
# here and open a fresh connection per call.
h_socket() {
  local line="$1"
  [ -z "${HERDR_SOCKET_PATH:-}" ] && return 0
  if command -v nc >/dev/null 2>&1; then
    printf '%s\n' "$line" | nc -U "$HERDR_SOCKET_PATH" 2>/dev/null | head -1
  else
    python3 -c "
import socket,sys
s=socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
try:
    s.settimeout(3)
    s.connect('$HERDR_SOCKET_PATH')
    s.sendall((sys.argv[1] + '\n').encode())
    print(s.makefile().readline().strip())
except Exception:
    pass
finally:
    s.close()
" "$line" 2>/dev/null
  fi
}
