# Shared helpers for herdr plugin scripts on Windows.
# Dot-source:  . "$PSScriptRoot\lib.ps1"
$ErrorActionPreference = 'Continue'

$script:Herdr = if ($env:HERDR_BIN_PATH) { $env:HERDR_BIN_PATH } else { 'herdr' }

# settings.ps1 is generated by the installer and lives next to these scripts.
. "$PSScriptRoot\settings.ps1"

function Get-HJson([string[]]$HerdrArgs) {
  try { (& $script:Herdr @HerdrArgs 2>$null | Out-String) | ConvertFrom-Json } catch { $null }
}

function Invoke-HNotify([string]$Title, [string]$Body = '', [string]$Sound = '') {
  $a = @('notification', 'show', $Title)
  if ($Body)  { $a += @('--body', $Body) }
  if ($Sound) { $a += @('--sound', $Sound) }
  & $script:Herdr @a *> $null
}

# --- Plugin JSON shapes (confirm with the calibration probe before trusting) ----
#
# HERDR_PLUGIN_CONTEXT_JSON is FLAT (actions and hooks alike):
#   workspace_id, workspace_label, workspace_cwd, tab_id, tab_label,
#   focused_pane_id, focused_pane_cwd, focused_pane_status,
#   invocation_source, correlation_id
#   + focused_pane_agent when an agent is detected
#   + worktree { repo_key, repo_name, repo_root, checkout_path, is_linked_worktree }
#     when the workspace is a worktree
#
# HERDR_PLUGIN_EVENT_JSON:
#   workspace.created -> { event, data { type, workspace { ..., worktree? } } }
#                        NOTE: no cwd, no branch
#   worktree.created  -> { event, data { type, workspace {...},
#                          worktree { path, branch, open_workspace_id, ... } } }
#
# BOTH events fire for the same new worktree. Anything hooked on workspace.created
# must skip worktrees or it runs twice.

function Get-HEventJson   { if ($env:HERDR_PLUGIN_EVENT_JSON)   { $env:HERDR_PLUGIN_EVENT_JSON   | ConvertFrom-Json } }
function Get-HContextJson { if ($env:HERDR_PLUGIN_CONTEXT_JSON) { $env:HERDR_PLUGIN_CONTEXT_JSON | ConvertFrom-Json } }

# herdr returns paths inconsistently: mixed separators in one string
# ("D:/Code/worktrees\repo\branch"), sometimes a \\?\ prefix, sometimes trailing \.
function Convert-HPath([string]$Path) {
  if (-not $Path) { return $null }
  ($Path -replace '^\\\\\?\\', '' -replace '/', '\').TrimEnd('\')
}

function Get-HWorkspaceId {
  # Set in plugin actions, event hooks and panes alike.
  if ($env:HERDR_WORKSPACE_ID) { return $env:HERDR_WORKSPACE_ID }
  (Get-HJson @('pane', 'current')).result.pane.workspace_id
}

function Get-HCwd {
  # Order matters. HERDR_ACTIVE_PANE_CWD / HERDR_ACTIVE_WORKSPACE_ID are NOT set in
  # plugin or keybinding context - relying on them silently falls through to the
  # process cwd, which is the plugin root and is not a git repo.
  # `workspace get` has no cwd field at all; only panes and worktrees carry a path.
  $ctx = Get-HContextJson
  if ($ctx) {
    if ($ctx.worktree.checkout_path) { return (Convert-HPath $ctx.worktree.checkout_path) }
    if ($ctx.focused_pane_cwd)       { return (Convert-HPath $ctx.focused_pane_cwd) }
    if ($ctx.workspace_cwd)          { return (Convert-HPath $ctx.workspace_cwd) }
  }
  if ($env:HERDR_PANE_ID) {
    $d = (Get-HJson @('pane', 'get', $env:HERDR_PANE_ID)).result.pane.cwd
    if ($d) { return (Convert-HPath $d) }
  }
  # Keybinding commands get no plugin context - ask the server for the focused pane.
  $d = (Get-HJson @('pane', 'current')).result.pane.cwd
  if ($d) { return (Convert-HPath $d) }
  return (Get-Location).Path
}

# `workspace list/get` has NO cwd field. For a worktree the path is
# worktree.checkout_path; otherwise it has to come from a pane.
function Get-HWorkspacePath([string]$WorkspaceId) {
  if (-not $WorkspaceId) { return $null }
  $w = (Get-HJson @('workspace', 'get', $WorkspaceId)).result.workspace
  if ($w.worktree.checkout_path) { return (Convert-HPath $w.worktree.checkout_path) }
  $p = (Get-HJson @('pane', 'list', '--workspace', $WorkspaceId)).result.panes |
         Where-Object { $_.cwd } | Select-Object -First 1
  if ($p) { return (Convert-HPath $p.cwd) }
  return $null
}

function Get-HGitRoot([string]$Dir) {
  if (-not $Dir) { $Dir = Get-HCwd }
  $r = git -C $Dir rev-parse --show-toplevel 2>$null
  if ($LASTEXITCODE -eq 0 -and $r) { return (Convert-HPath $r) }
  return $null
}

function Get-HBaseBranch([string]$Dir) {
  $b = git -C $Dir symbolic-ref -q --short refs/remotes/origin/HEAD 2>$null
  if ($b) { return $b.Trim() }
  foreach ($c in 'origin/main', 'origin/master', 'main', 'master') {
    git -C $Dir rev-parse --verify -q $c *> $null
    if ($LASTEXITCODE -eq 0) { return $c }
  }
  return 'HEAD'
}

function Get-HSlug([string]$Text) {
  $s = ($Text.ToLowerInvariant() -replace '[^a-z0-9]+', '-').Trim('-')
  if ($s -notmatch '^[a-z]') { $s = "a$s" }
  if ($s.Length -gt 32) { $s = $s.Substring(0, 32) }
  return $s
}

function Get-HPaneOfWorkspace([string]$WorkspaceId) {
  $j = Get-HJson @('pane', 'list', '--workspace', $WorkspaceId)
  $p = $j.result.panes | Where-Object { $_.focused } | Select-Object -First 1
  if (-not $p) { $p = $j.result.panes | Select-Object -First 1 }
  $p.pane_id
}

# `agent start` needs a pane already sitting at an interactive shell prompt. It never
# creates or moves panes. Everything after `--` is passed through to the agent.
function Start-HAgent([string]$PaneId, [string]$Label, [string]$Prompt = '') {
  $name = "a-$(Get-HSlug $Label)"
  if ($name.Length -gt 32) { $name = $name.Substring(0, 32) }
  $live = (Get-HJson @('agent', 'list')).result.agents.name
  if ($live -contains $name) {
    $name = "$($name.Substring(0, [Math]::Min(27, $name.Length)))-$(Get-Random -Max 9999)"
  }

  $ok = $false; $out = ''
  foreach ($i in 1..6) {
    $out = & $script:Herdr agent start $name --kind $global:AgentKind --pane $PaneId -- @global:AgentArgs 2>&1 | Out-String
    if ($out -notmatch '"error"') { $ok = $true; break }
    Start-Sleep -Milliseconds 1500
  }
  if (-not $ok) { Write-Host "agent start failed: $out" -ForegroundColor Red; return $null }
  if ($Prompt) { & $script:Herdr agent prompt $name $Prompt *> $null }
  return $name
}

# Raw socket API. On Windows HERDR_SOCKET_PATH is a named pipe whose name is LITERALLY
# that path ("C:\Users\...\herdr\herdr.sock") - no \\.\pipe\ prefix is stripped. A file
# of the same name exists on disk but holds only "<pid>:<nonce>"; no data flows through
# it. The server is one-shot: it closes after one request/response, so every call opens
# a fresh connection.
function Invoke-HSocket([string]$JsonLine) {
  $pipe = $env:HERDR_SOCKET_PATH
  if (-not $pipe) { return $null }
  try {
    $c = New-Object System.IO.Pipes.NamedPipeClientStream('.', $pipe, [System.IO.Pipes.PipeDirection]::InOut)
    $c.Connect(2000)
    $enc = New-Object System.Text.UTF8Encoding($false)
    $w = New-Object System.IO.StreamWriter($c, $enc); $w.AutoFlush = $true
    $r = New-Object System.IO.StreamReader($c, $enc)
    $w.WriteLine($JsonLine)
    $line = $r.ReadLine()
    $c.Dispose()
    return $line
  } catch { return $null }
}
